version: "3"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    volumes:
      - /root/vw-data/:/data
    ports:
      - "86:80"

  alist:
    image: xhofe/alist
    container_name: alist
    restart: always
    ports:
      - "5244:5244"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    volumes:
      - /etc/alist:/opt/alist/data

  chatgpt-web:
    image: chenzhaoyu94/chatgpt-web
    ports:
      - 3002:3002
    environment:
      - OPENAI_API_KEY=xxxxxx
      - OPENAI_ACCESS_TOKEN=xxxxxx
      - OPENAI_API_BASE_URL=xxxx
      - OPENAI_API_MODEL=xxxx
      - API_REVERSE_PROXY=xxx
      - AUTH_SECRET_KEY=xxx
      - MAX_REQUEST_PER_HOUR=0
      - TIMEOUT_MS=60000
      - SOCKS_PROXY_HOST=xxxx
      - SOCKS_PROXY_PORT=xxxx

  mcserver:
    image: marctv/minecraft-papermc-server:latest
    container_name: mcserver
    restart: unless-stopped
    environment:
      - MEMORYSIZE=1G
      - PAPERMC_FLAGS=
    volumes:
      - /root/mcserver:/data:rw
    ports:
      - "25565:25565"
    tty: true

  nginx:
    image: jc21/nginx-proxy-manager
    restart: unless-stopped
    network_mode: host
    volumes:
      - /root/data:/data
      - /root/letsencrypt:/etc/letsencrypt

  qinglong:
    image: whyour/qinglong
    container_name: qinglong
    hostname: qinglong
    restart: unless-stopped
    ports:
      - 5700:5700
    volumes:
      - /root/ql/data:/ql/data

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --cleanup

  btpanel:
    image: btpanel/baota:lnmp
    container_name: aapanel
    network_mode: host
    restart: unless-stopped
    volumes:
      - /root/website_data:/www/wwwroot
      - /root/mysql_data:/www/server/data
      - /root/vhost:/www/server/panel/vhost
